package ec.edu.uce.modelo;

public enum Categoria {

	CAFETERIA, HUEVOS, ARTESANIAS, FRUTAS_VERDURAS, BEBIDAS, CARNES, CERVEZAS, CONDIMENTOS, EMBUTIDOS, FERRETERIA,
	GALLETERIA, GOLOSINAS, HELADOS, LACTEOS, LEGUMBRES, LICORES, LIMPIEZA, MEDICINAS, PANADERIA, PAPELERIA, PLASTICOS,
	SALSAS, SALUD_HIGIENE, SNACKS, TABACOS, TECNOLOGIA, VIVERES
}
